Change error messages

diff --git a/.gitfiles/.git_template/hooks/pre-push b/.gitfiles/.git_template/hooks/pre-push
--- a/.gitfiles/.git_template/hooks/pre-push
+++ b/.gitfiles/.git_template/hooks/pre-push
@@ -3,7 +3,7 @@
 # if the branch is master, then fail.
 branch="$(git symbolic-ref HEAD 2>/dev/null)" || "$(git describe --contains --all HEAD)"
 if [ "${branch##refs/heads/}" = "master" ]; then
-	echo "Can't push to the MASTER branch!"
-	echo "If you want to push to the master branch, please run 'git push --no-verify'."
-	exit 1
+    echo "error: SHOULD NOT push to the master branch!"
+    echo "If you really want to push to the master branch, please run 'git push --no-verify'."
+    exit 1
 fi
